name: Test Action
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: juliangruber/read-file-action@v1
        id: package
        with:
          path: ./test.json
      - name: Echo file sha256
        run: echo "${{ fromJson(steps.package.outputs.content).sha256sum }}"
        
      - name: Create latest.json File
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "nightly.json"
          json: '{"versionCode":"250", "versionName":"2.5.0", "sha256sum": "${{ fromJson(steps.package.outputs.content).sha256sum }}", "url": "https:"}'
      - run: echo '{"versionCode":"250", "versionName":"2.5.0", "sha256sum":"${{ fromJson(steps.package.outputs.content).sha256sum }}", "url":"https:"}'
