name: CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - uses: juliangruber/read-file-action@v1
        id: package
        with:
          path: ./nightly.json
      - name: Echo file sha256
        run: echo "${{ fromJson(steps.package.outputs.content).sha256sum }}"
