name: Test Action
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: juliangruber/read-file-action@v1
        id: package
        with:
          path: ./nightly.json
      - name: Echo file sha256
        run: echo "${{ fromJson(steps.package.outputs.content).sha256sum }}"
